# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7481b4db8d3ec7b1cba239c6dfafb629f691c767f3fd8f177a0d91bb6332d5fae892e8bcc1baeb90b7da514a393cd4babcc16f3cb0f80e95fff99055391823e

test:
  secret_key_base: 1cb0a4e33b24be0d3488f38545f53838eac1a194ad008d81d9b28fe7e0fb510c5c606a8d66457b6f40649b5b13495b4ee3ac94f2043e3e8d3820b9b3c4b38565

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
